export default {
    rickAndMorty: 'Rick and Morty',
    passwordInputDescription:
      'Adding capitals, numbers and punctuation will make your password stronger',
    strengthenYourPassword:
      'Strengthen password by adding capitals, numbers and ponctuation',
    passwordStrength: 'Password strength:',
    tooShort: 'Your password must be at least 6 characters long',
    tooWeak: 'Too weak',
    medium: 'Medium',
    strong: 'Strong',
    requiredField: 'This field is required',
    requiredField2: 'Please enter your {{fieldName}}',
    noLongerThan: "This field can't have more than {{length}} characters",
    searchPlaceholder: 'Search characters by name...',
    business_one: 'Business',
    business_other: 'Businesses',
    businesses: 'Businesses',
    news: 'News',
    emailValidation: 'Invalid email address',
    noKey: 'No key',
    no: 'No',
    yes: 'Yes',
    cancel: 'Cancel',
    ok: 'Ok',
    email: 'Email',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    sessionExpired: 'Session expired',
    forbiddenRedirectMessage: 'Forbidden request',
    loggingInProgress: 'Logging in...',
    login: 'Login',
    logout: 'Log out',
    loginFailed: 'Login failed',
    invalidCredentials: 'Invalid login credentials',
    previousSessionExpired: 'Previous session expired',
    serverError: 'Server error',
    error: 'Error',
    invalidPassword: 'Invalid password',
    invalidEmail: 'Invalid email',
    signUp: 'Sign Up',
    by: 'by',
    signUpFailed: 'Sign Up failed',
    signingInProgress: 'Signing in...',
    passwordsDoNotMatch: 'Passwords do not match',
    signupError: 'There was an error during signup. Please try again later.',
    forgotPassword: 'Forgot Password',
    fieldsAreNotEqual: 'The fields do not match',
    poweredBy: 'Powered by',
    invalidCredentialsForReseting: 'Invalid email or password.',
    resetPasswordFailed: 'Failed to reset password. Please try again.',
    resetInProgress: 'Reseting password...',
    resetPassword: 'Reset password',
    forgotPasswordFailed: 'Forgot password request failed',
    forgotPasswordSuccess:
      'Forgot password request sent successfully, please go check your email.',
    sendingEmail: 'Sending email for reseting...',
    invalidToken: 'Your token is not valid. Please try again.',
    fetchUserDataFailed: 'Failed to fetch user data',
    resetPasswordSuccess: 'Password reset successfully.',
    password: 'Password',
    logoutSuccess: 'Logged out successfully!',
    username: 'Username',
    loading: 'Loading',
    submit: 'Submit',
    allRightsReserved: 'All rights reserved.',
    pageNotFound: '404 - Page Not Found',
    goTo: 'Go to',
    loginPage: 'Login Page',
    headerTitle: 'Rick & Morty',
    characters: 'Characters',
    footerText:  'Rick and Morty Fan App. All rights reserved.',
    episode: 'Episode:',
    airDate: 'Air date:',
    status: 'Status:',
    gender: 'Gender:',
    species: 'Species:',
    location: 'Location:',
    episodes: 'Episodes',
    type:'Type:',
    dimension: 'Dimension:',
    residents: 'Residents:',
    emailAlreadyExists: "This email is already registered",
    charactersPage: 'Characters page',
  } as const;
  